name: LittleLearner
options:
  bundleIdPrefix: com.antonlehuy
  deploymentTarget:
    iOS: "17.0"
targets:
  LittleLearner:
    type: application
    platform: iOS
    sources:
      - path: Sources/LittleLearner
    info:
      path: Generated-Info.plist
      properties:
        UIAppFonts:
          - Baloo2-ExtraBold.ttf
          - BeVietnamPro-Regular.ttf
          - BeVietnamPro-SemiBold.ttf
          - BeVietnamPro-Bold.ttf
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.antonlehuy.littlelearner
        PRODUCT_NAME: LittleLearner
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        INFOPLIST_KEY_UISupportedInterfaceOrientations: UIInterfaceOrientationPortrait
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: YDD4626MUX
  LittleLearnerSnapshotTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests/LittleLearnerSnapshotTests
    dependencies:
      - target: LittleLearner
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.antonlehuy.littlelearner.SnapshotTests
        SWIFT_VERSION: "5.0"
        GENERATE_INFOPLIST_FILE: YES
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: YDD4626MUX
schemes:
  LittleLearner:
    build:
      targets:
        LittleLearner: all
        LittleLearnerSnapshotTests: [test]
    test:
      targets:
        - LittleLearnerSnapshotTests
