import Foundation

enum VocabularyContent {
    static let categories: [VocabularyCategory] = [
        VocabularyCategory(id: "animals", title: "Con vật", symbolName: "pawprint.fill", imageName: nil, colorHex: "#FF9F43"),
        VocabularyCategory(id: "story", title: "Từ trong truyện", symbolName: "book.fill", imageName: "hoang_tu_va_cao", colorHex: "#4FC3F7"),
        VocabularyCategory(id: "colors", title: "Màu sắc", symbolName: "paintpalette.fill", imageName: nil, colorHex: "#5F27CD"),
        VocabularyCategory(id: "numbers", title: "Số đếm", symbolName: "textformat.123", imageName: nil, colorHex: "#2ED8B6"),
    ]

    static let cards: [VocabularyCard] = [
        VocabularyCard(id: "animal_dog", word: "Dog", translation: "Con chó", emoji: "🐶", symbolName: "dog.fill", imageName: "animal_dog", categoryId: "animals", description: "Chó là bạn thân của con người, thích vẫy đuôi mừng rỡ."),
        VocabularyCard(id: "animal_cat", word: "Cat", translation: "Con mèo", emoji: "🐱", symbolName: "cat.fill", imageName: "animal_cat", categoryId: "animals", description: "Mèo có bộ ria dài và thích nằm sưởi nắng."),
        VocabularyCard(id: "animal_bird", word: "Bird", translation: "Con chim", emoji: "🐦", symbolName: "bird.fill", imageName: "animal_bird", categoryId: "animals", description: "Chim có đôi cánh nhỏ và biết bay trên bầu trời."),
        VocabularyCard(id: "animal_fish", word: "Fish", translation: "Con cá", emoji: "🐟", symbolName: "fish.fill", imageName: "animal_fish", categoryId: "animals", description: "Cá sống dưới nước và bơi bằng vây."),
        VocabularyCard(id: "animal_rabbit", word: "Rabbit", translation: "Con thỏ", emoji: "🐰", symbolName: "hare.fill", imageName: "animal_rabbit", categoryId: "animals", description: "Thỏ có đôi tai dài và thích ăn cà rốt."),
        VocabularyCard(id: "animal_bear", word: "Bear", translation: "Con gấu", emoji: "🐻", symbolName: nil, imageName: "animal_bear", categoryId: "animals", description: "Gấu có bộ lông dày và rất thích mật ong."),
        VocabularyCard(id: "animal_lion", word: "Lion", translation: "Con sư tử", emoji: "🦁", symbolName: nil, imageName: "animal_lion", categoryId: "animals", description: "Sư tử có bờm to và được gọi là chúa tể rừng xanh."),
        VocabularyCard(id: "animal_elephant", word: "Elephant", translation: "Con voi", emoji: "🐘", symbolName: nil, imageName: "animal_elephant", categoryId: "animals", description: "Voi có cái vòi dài và đôi tai rất to."),
        VocabularyCard(id: "animal_hamster", word: "Hamster", translation: "Chuột hamster", emoji: "🐹", symbolName: nil, imageName: "animal_hamster", categoryId: "animals", description: "Hamster nhỏ xíu, thích nhét thức ăn vào túi má."),
        VocabularyCard(id: "animal_cow", word: "Cow", translation: "Con bò", emoji: "🐄", symbolName: nil, imageName: "animal_cow", categoryId: "animals", description: "Bò cho chúng ta sữa để uống mỗi ngày."),
        VocabularyCard(id: "animal_pig", word: "Pig", translation: "Con lợn", emoji: "🐷", symbolName: nil, imageName: "animal_pig", categoryId: "animals", description: "Lợn có cái mũi hếch và thích lăn trong bùn."),
        VocabularyCard(id: "animal_chicken", word: "Chicken", translation: "Con gà", emoji: "🐔", symbolName: nil, imageName: "animal_chicken", categoryId: "animals", description: "Gà mái đẻ trứng, gà trống gáy vang buổi sáng."),
        VocabularyCard(id: "animal_turkey", word: "Turkey", translation: "Gà tây", emoji: "🦃", symbolName: nil, imageName: "animal_turkey", categoryId: "animals", description: "Gà tây có bộ lông xòe to như cái quạt."),
        VocabularyCard(id: "animal_tiger", word: "Tiger", translation: "Con hổ", emoji: "🐯", symbolName: nil, imageName: "animal_tiger", categoryId: "animals", description: "Hổ có bộ lông vằn và chạy rất nhanh."),
        VocabularyCard(id: "animal_gorilla", word: "Gorilla", translation: "Khỉ đột", emoji: "🦍", symbolName: nil, imageName: "animal_gorilla", categoryId: "animals", description: "Khỉ đột rất khỏe và sống thành đàn trong rừng."),
        VocabularyCard(id: "animal_monkey", word: "Monkey", translation: "Con khỉ", emoji: "🐒", symbolName: nil, imageName: "animal_monkey", categoryId: "animals", description: "Khỉ leo trèo giỏi và thích ăn chuối."),
        VocabularyCard(id: "animal_koala", word: "Koala", translation: "Gấu koala", emoji: "🐨", symbolName: nil, imageName: "animal_koala", categoryId: "animals", description: "Koala ôm cây và ngủ gần cả ngày."),
        VocabularyCard(id: "animal_fox", word: "Fox", translation: "Con cáo", emoji: "🦊", symbolName: nil, imageName: "animal_fox", categoryId: "animals", description: "Cáo có bộ lông màu cam và cái đuôi rất to."),
        VocabularyCard(id: "animal_deer", word: "Deer", translation: "Con hươu", emoji: "🦌", symbolName: nil, imageName: "animal_deer", categoryId: "animals", description: "Hươu có đôi sừng đẹp và chạy nhảy trong rừng."),
        VocabularyCard(id: "animal_owl", word: "Owl", translation: "Con cú", emoji: "🦉", symbolName: nil, imageName: "animal_owl", categoryId: "animals", description: "Cú thức đêm và quay đầu được rất xa."),
        VocabularyCard(id: "animal_parrot", word: "Parrot", translation: "Con vẹt", emoji: "🦜", symbolName: nil, imageName: "animal_parrot", categoryId: "animals", description: "Vẹt có bộ lông sặc sỡ và biết bắt chước tiếng nói."),
        VocabularyCard(id: "animal_penguin", word: "Penguin", translation: "Chim cánh cụt", emoji: "🐧", symbolName: nil, imageName: "animal_penguin", categoryId: "animals", description: "Cánh cụt không biết bay nhưng bơi rất giỏi."),
        VocabularyCard(id: "animal_flamingo", word: "Flamingo", translation: "Hồng hạc", emoji: "🦩", symbolName: nil, imageName: "animal_flamingo", categoryId: "animals", description: "Hồng hạc có lông màu hồng và thích đứng một chân."),
        VocabularyCard(id: "animal_swan", word: "Swan", translation: "Thiên nga", emoji: "🦢", symbolName: nil, imageName: "animal_swan", categoryId: "animals", description: "Thiên nga có cổ dài và bơi rất duyên dáng."),
        VocabularyCard(id: "animal_toucan", word: "Toucan", translation: "Chim toucan", emoji: "🐦", symbolName: nil, imageName: "animal_toucan", categoryId: "animals", description: "Toucan có cái mỏ to và nhiều màu sắc."),
        VocabularyCard(id: "animal_sparrow", word: "Sparrow", translation: "Chim sẻ", emoji: "🐦", symbolName: nil, imageName: "animal_sparrow", categoryId: "animals", description: "Chim sẻ nhỏ bé, hay líu lo trên mái nhà."),
        VocabularyCard(id: "animal_pelican", word: "Pelican", translation: "Bồ nông", emoji: "🐦", symbolName: nil, imageName: "animal_pelican", categoryId: "animals", description: "Bồ nông có cái túi to dưới mỏ để đựng cá."),
        VocabularyCard(id: "animal_hummingbird", word: "Hummingbird", translation: "Chim ruồi", emoji: "🐦", symbolName: nil, imageName: "animal_hummingbird", categoryId: "animals", description: "Chim ruồi vỗ cánh rất nhanh và bay đứng tại chỗ được."),
        VocabularyCard(id: "animal_whale", word: "Whale", translation: "Cá voi", emoji: "🐋", symbolName: nil, imageName: "animal_whale", categoryId: "animals", description: "Cá voi là loài vật to lớn nhất sống dưới biển."),
        VocabularyCard(id: "animal_crab", word: "Crab", translation: "Con cua", emoji: "🦀", symbolName: nil, imageName: "animal_crab", categoryId: "animals", description: "Cua có hai càng to và đi ngang."),
        VocabularyCard(id: "animal_lobster", word: "Lobster", translation: "Tôm hùm", emoji: "🦞", symbolName: nil, imageName: "animal_lobster", categoryId: "animals", description: "Tôm hùm có lớp vỏ cứng và hai càng to khỏe."),
        VocabularyCard(id: "animal_shrimp", word: "Shrimp", translation: "Con tôm", emoji: "🦐", symbolName: nil, imageName: "animal_shrimp", categoryId: "animals", description: "Tôm có thân cong và bơi giật lùi."),
        VocabularyCard(id: "animal_jellyfish", word: "Jellyfish", translation: "Sứa biển", emoji: "🪼", symbolName: nil, imageName: "animal_jellyfish", categoryId: "animals", description: "Sứa có thân trong suốt và bơi lững lờ trong nước."),
        VocabularyCard(id: "animal_starfish", word: "Starfish", translation: "Sao biển", emoji: "⭐", symbolName: nil, imageName: "animal_starfish", categoryId: "animals", description: "Sao biển có năm cánh tay hình ngôi sao."),
        VocabularyCard(id: "animal_turtle", word: "Turtle", translation: "Con rùa", emoji: "🐢", symbolName: nil, imageName: "animal_turtle", categoryId: "animals", description: "Rùa mang theo cái mai cứng và bò rất chậm."),
        VocabularyCard(id: "animal_squid", word: "Squid", translation: "Con mực", emoji: "🦑", symbolName: nil, imageName: "animal_squid", categoryId: "animals", description: "Mực có nhiều xúc tu và phun mực đen khi sợ."),
        VocabularyCard(id: "animal_crocodile", word: "Crocodile", translation: "Cá sấu", emoji: "🐊", symbolName: nil, imageName: "animal_crocodile", categoryId: "animals", description: "Cá sấu có hàm răng sắc và thích nằm im dưới nước."),
        VocabularyCard(id: "animal_frog", word: "Frog", translation: "Con ếch", emoji: "🐸", symbolName: nil, imageName: "animal_frog", categoryId: "animals", description: "Ếch nhảy giỏi và kêu ộp ộp vào ban đêm."),
        VocabularyCard(id: "animal_salamander", word: "Salamander", translation: "Kỳ giông", emoji: "🦎", symbolName: nil, imageName: "animal_salamander", categoryId: "animals", description: "Kỳ giông có làn da ẩm và thích sống gần nước."),
        VocabularyCard(id: "animal_butterfly", word: "Butterfly", translation: "Con bướm", emoji: "🦋", symbolName: nil, imageName: "animal_butterfly", categoryId: "animals", description: "Bướm có đôi cánh sặc sỡ và bay từ hoa này sang hoa khác."),
        VocabularyCard(id: "animal_snail", word: "Snail", translation: "Ốc sên", emoji: "🐌", symbolName: nil, imageName: "animal_snail", categoryId: "animals", description: "Ốc sên mang cái vỏ xoắn trên lưng và bò rất chậm."),
        VocabularyCard(id: "animal_beetle", word: "Beetle", translation: "Bọ cánh cứng", emoji: "🪲", symbolName: nil, imageName: "animal_beetle", categoryId: "animals", description: "Bọ cánh cứng có lớp vỏ ngoài cứng như áo giáp."),
        VocabularyCard(id: "animal_mouse", word: "Mouse", translation: "Con chuột", emoji: "🐭", symbolName: nil, imageName: "animal_mouse", categoryId: "animals", description: "Chuột nhỏ xíu, chạy nhanh và thích gặm nhấm."),
        VocabularyCard(id: "animal_squirrel", word: "Squirrel", translation: "Con sóc", emoji: "🐿️", symbolName: nil, imageName: "animal_squirrel", categoryId: "animals", description: "Sóc có cái đuôi to xù và giỏi leo cây."),
        VocabularyCard(id: "animal_cheetah", word: "Cheetah", translation: "Báo săn", emoji: "🐆", symbolName: nil, imageName: "animal_cheetah", categoryId: "animals", description: "Báo săn là loài vật chạy nhanh nhất trên cạn."),
        VocabularyCard(id: "animal_rhinoceros", word: "Rhinoceros", translation: "Tê giác", emoji: "🦏", symbolName: nil, imageName: "animal_rhinoceros", categoryId: "animals", description: "Tê giác có cái sừng to trên mũi và làn da dày."),
        VocabularyCard(id: "animal_hippopotamus", word: "Hippopotamus", translation: "Hà mã", emoji: "🦛", symbolName: nil, imageName: "animal_hippopotamus", categoryId: "animals", description: "Hà mã to lớn và thích ngâm mình dưới nước."),
        VocabularyCard(id: "animal_zebra", word: "Zebra", translation: "Ngựa vằn", emoji: "🦓", symbolName: nil, imageName: "animal_zebra", categoryId: "animals", description: "Ngựa vằn có những sọc đen trắng trên khắp mình."),
        VocabularyCard(id: "animal_donkey", word: "Donkey", translation: "Con lừa", emoji: "🫏", symbolName: nil, imageName: "animal_donkey", categoryId: "animals", description: "Lừa chăm chỉ thồ hàng và kêu be be."),
        VocabularyCard(id: "animal_duck", word: "Duck", translation: "Con vịt", emoji: "🦆", symbolName: nil, imageName: "animal_duck", categoryId: "animals", description: "Vịt có chân màng và bơi giỏi dưới nước."),
        VocabularyCard(id: "animal_sheep", word: "Sheep", translation: "Con cừu", emoji: "🐑", symbolName: nil, imageName: "animal_sheep", categoryId: "animals", description: "Cừu có bộ lông xoăn dùng để dệt len."),
        VocabularyCard(id: "animal_horse", word: "Horse", translation: "Con ngựa", emoji: "🐴", symbolName: nil, imageName: "animal_horse", categoryId: "animals", description: "Ngựa có bờm dài và chạy rất nhanh."),
        VocabularyCard(id: "animal_eagle", word: "Eagle", translation: "Đại bàng", emoji: "🦅", symbolName: nil, imageName: "animal_eagle", categoryId: "animals", description: "Đại bàng bay cao và có đôi mắt rất tinh."),
        VocabularyCard(id: "animal_camel", word: "Camel", translation: "Lạc đà", emoji: "🐫", symbolName: nil, imageName: "animal_camel", categoryId: "animals", description: "Lạc đà có bướu trên lưng để trữ nước đi sa mạc."),
        VocabularyCard(id: "animal_wolf", word: "Wolf", translation: "Con sói", emoji: "🐺", symbolName: nil, imageName: "animal_wolf", categoryId: "animals", description: "Sói sống theo bầy và hay tru vào ban đêm."),
        VocabularyCard(id: "animal_panda", word: "Panda", translation: "Gấu trúc", emoji: "🐼", symbolName: nil, imageName: "animal_panda", categoryId: "animals", description: "Gấu trúc có bộ lông đen trắng và thích ăn tre."),
        VocabularyCard(id: "animal_kangaroo", word: "Kangaroo", translation: "Chuột túi", emoji: "🦘", symbolName: nil, imageName: "animal_kangaroo", categoryId: "animals", description: "Chuột túi nhảy bằng hai chân sau và có túi trước bụng."),
        VocabularyCard(id: "animal_beaver", word: "Beaver", translation: "Hải ly", emoji: "🦫", symbolName: nil, imageName: "animal_beaver", categoryId: "animals", description: "Hải ly dùng răng gặm cây để xây đập."),
        VocabularyCard(id: "animal_dolphin", word: "Dolphin", translation: "Cá heo", emoji: "🐬", symbolName: nil, imageName: "animal_dolphin", categoryId: "animals", description: "Cá heo thông minh và thích nhảy trên mặt biển."),
        VocabularyCard(id: "animal_scorpion", word: "Scorpion", translation: "Bọ cạp", emoji: "🦂", symbolName: nil, imageName: "animal_scorpion", categoryId: "animals", description: "Bọ cạp có cái đuôi cong với nọc độc ở đầu."),
        VocabularyCard(id: "animal_ladybug", word: "Ladybug", translation: "Bọ rùa", emoji: "🐞", symbolName: nil, imageName: "animal_ladybug", categoryId: "animals", description: "Bọ rùa có lớp vỏ đỏ chấm đen xinh xắn."),
        VocabularyCard(id: "animal_toad", word: "Toad", translation: "Con cóc", emoji: "🐸", symbolName: nil, imageName: "animal_toad", categoryId: "animals", description: "Cóc có làn da sần sùi và hay ở nơi ẩm ướt."),
        VocabularyCard(id: "animal_seahorse", word: "Seahorse", translation: "Cá ngựa", emoji: "🐴", symbolName: nil, imageName: "animal_seahorse", categoryId: "animals", description: "Cá ngựa có hình dáng giống ngựa và bơi thẳng đứng."),
        VocabularyCard(id: "animal_worm", word: "Worm", translation: "Con giun", emoji: "🪱", symbolName: nil, imageName: "animal_worm", categoryId: "animals", description: "Giun sống trong đất và giúp đất tơi xốp."),
        VocabularyCard(id: "animal_bee", word: "Bee", translation: "Con ong", emoji: "🐝", symbolName: nil, imageName: "animal_bee", categoryId: "animals", description: "Ong bay từ hoa này sang hoa khác để làm mật."),
        VocabularyCard(id: "animal_hedgehog", word: "Hedgehog", translation: "Con nhím", emoji: "🦔", symbolName: nil, imageName: "animal_hedgehog", categoryId: "animals", description: "Nhím có nhiều gai nhọn để tự bảo vệ mình."),
        VocabularyCard(id: "animal_snake", word: "Snake", translation: "Con rắn", emoji: "🐍", symbolName: nil, imageName: "animal_snake", categoryId: "animals", description: "Rắn không có chân, trườn bằng cách uốn mình."),
        VocabularyCard(id: "animal_octopus", word: "Octopus", translation: "Bạch tuộc", emoji: "🐙", symbolName: nil, imageName: "animal_octopus", categoryId: "animals", description: "Bạch tuộc có tám xúc tu và rất thông minh."),
        VocabularyCard(id: "animal_walrus", word: "Walrus", translation: "Hải mã", emoji: "🦭", symbolName: nil, imageName: "animal_walrus", categoryId: "animals", description: "Hải mã có hai chiếc ngà dài và làn da dày."),
        VocabularyCard(id: "animal_shark", word: "Shark", translation: "Cá mập", emoji: "🦈", symbolName: nil, imageName: "animal_shark", categoryId: "animals", description: "Cá mập bơi rất giỏi và có hàm răng sắc nhọn."),
        VocabularyCard(id: "animal_seal", word: "Seal", translation: "Hải cẩu", emoji: "🦭", symbolName: nil, imageName: "animal_seal", categoryId: "animals", description: "Hải cẩu bơi giỏi và thích nằm phơi nắng trên đá."),
        VocabularyCard(id: "animal_chameleon", word: "Chameleon", translation: "Tắc kè hoa", emoji: "🦎", symbolName: nil, imageName: "animal_chameleon", categoryId: "animals", description: "Tắc kè hoa đổi màu da để lẫn vào xung quanh."),
        VocabularyCard(id: "animal_moose", word: "Moose", translation: "Nai sừng tấm", emoji: "🫎", symbolName: nil, imageName: "animal_moose", categoryId: "animals", description: "Nai sừng tấm có cặp sừng to như cành cây."),
        VocabularyCard(id: "animal_bat", word: "Bat", translation: "Con dơi", emoji: "🦇", symbolName: nil, imageName: "animal_bat", categoryId: "animals", description: "Dơi bay vào ban đêm và ngủ treo ngược trên cây."),
        VocabularyCard(id: "animal_spider", word: "Spider", translation: "Con nhện", emoji: "🕷️", symbolName: nil, imageName: "animal_spider", categoryId: "animals", description: "Nhện có tám chân và giăng tơ để bắt mồi."),
        VocabularyCard(id: "animal_gecko", word: "Gecko", translation: "Thạch sùng", emoji: "🦎", symbolName: nil, imageName: "animal_gecko", categoryId: "animals", description: "Thạch sùng leo tường giỏi và hay bắt muỗi."),
        VocabularyCard(id: "animal_firefly", word: "Firefly", translation: "Đom đóm", emoji: "✨", symbolName: nil, imageName: "animal_firefly", categoryId: "animals", description: "Đom đóm phát sáng lập lòe vào ban đêm."),
        VocabularyCard(id: "animal_sloth", word: "Sloth", translation: "Con lười", emoji: "🦥", symbolName: nil, imageName: "animal_sloth", categoryId: "animals", description: "Con lười di chuyển rất chậm và ngủ suốt ngày."),
        VocabularyCard(id: "animal_mosquito", word: "Mosquito", translation: "Con muỗi", emoji: "🦟", symbolName: nil, imageName: "animal_mosquito", categoryId: "animals", description: "Muỗi bay vo ve và thích hút máu vào ban đêm."),
        VocabularyCard(id: "animal_ant", word: "Ant", translation: "Con kiến", emoji: "🐜", symbolName: nil, imageName: "animal_ant", categoryId: "animals", description: "Kiến nhỏ bé nhưng rất chăm chỉ và sống theo đàn."),
        VocabularyCard(id: "animal_otter", word: "Otter", translation: "Rái cá", emoji: "🦦", symbolName: nil, imageName: "animal_otter", categoryId: "animals", description: "Rái cá bơi giỏi và thích nắm tay nhau khi ngủ."),
        VocabularyCard(id: "animal_iguana", word: "Iguana", translation: "Kỳ nhông", emoji: "🦎", symbolName: nil, imageName: "animal_iguana", categoryId: "animals", description: "Kỳ nhông có làn da sần và thích phơi nắng."),
        VocabularyCard(id: "animal_raccoon", word: "Raccoon", translation: "Gấu mèo", emoji: "🦝", symbolName: nil, imageName: "animal_raccoon", categoryId: "animals", description: "Gấu mèo có vệt lông đen quanh mắt như đeo mặt nạ."),
        VocabularyCard(id: "animal_dragonfly", word: "Dragonfly", translation: "Chuồn chuồn", emoji: "🐉", symbolName: nil, imageName: "animal_dragonfly", categoryId: "animals", description: "Chuồn chuồn có đôi cánh mỏng và bay lượn trên mặt nước."),
        VocabularyCard(id: "animal_grasshopper", word: "Grasshopper", translation: "Châu chấu", emoji: "🦗", symbolName: nil, imageName: "animal_grasshopper", categoryId: "animals", description: "Châu chấu có chân sau khỏe, nhảy rất xa."),
        VocabularyCard(id: "animal_skunk", word: "Skunk", translation: "Chồn hôi", emoji: "🦨", symbolName: nil, imageName: "animal_skunk", categoryId: "animals", description: "Chồn hôi xịt mùi hôi để xua đuổi kẻ thù."),

        VocabularyCard(id: "color_red", word: "Red", translation: "Đỏ", emoji: "🔴", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#E2503F"),
        VocabularyCard(id: "color_blue", word: "Blue", translation: "Xanh dương", emoji: "🔵", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#5B8FC7"),
        VocabularyCard(id: "color_yellow", word: "Yellow", translation: "Vàng", emoji: "🟡", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#E8B84E"),
        VocabularyCard(id: "color_green", word: "Green", translation: "Xanh lá", emoji: "🟢", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#7FB37A"),
        VocabularyCard(id: "color_orange", word: "Orange", translation: "Cam", emoji: "🟠", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#E2924F"),
        VocabularyCard(id: "color_purple", word: "Purple", translation: "Tím", emoji: "🟣", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#A78FC9"),
        VocabularyCard(id: "color_pink", word: "Pink", translation: "Hồng", emoji: "🩷", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#F0A8BE"),
        VocabularyCard(id: "color_black", word: "Black", translation: "Đen", emoji: "⚫", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#6B6660"),

        VocabularyCard(id: "story_fox", word: "Fox", translation: "Con cáo", emoji: "🦊", symbolName: nil, imageName: "ch1_ice_fox", categoryId: "story"),
        VocabularyCard(id: "story_penguin", word: "Penguin", translation: "Chim cánh cụt", emoji: "🐧", symbolName: nil, imageName: "chim_canh_cut_portrait", categoryId: "story"),
        VocabularyCard(id: "story_laugh", word: "Laugh", translation: "Tiếng cười", emoji: "😄", symbolName: nil, imageName: "ch2_penguin_laugh", categoryId: "story"),
        VocabularyCard(id: "story_lantern", word: "Lantern", translation: "Đèn lồng", emoji: "🔦", symbolName: nil, imageName: "den_portrait", categoryId: "story"),
        VocabularyCard(id: "story_brave", word: "Brave", translation: "Dũng cảm", emoji: "🦸", symbolName: nil, imageName: "ch3_lantern_boy", categoryId: "story"),
        VocabularyCard(id: "story_storm", word: "Storm", translation: "Bão tuyết", emoji: "🌪️", symbolName: nil, imageName: "witch_portrait", categoryId: "story"),
        VocabularyCard(id: "story_witch", word: "Witch", translation: "Phù thủy", emoji: "🧙", symbolName: nil, imageName: "witch_portrait", categoryId: "story"),
        VocabularyCard(id: "story_friend", word: "Friend", translation: "Người bạn", emoji: "🤝", symbolName: nil, imageName: "ch5_ending", categoryId: "story"),

        VocabularyCard(id: "number_one", word: "One", translation: "Một", emoji: "1️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 1),
        VocabularyCard(id: "number_two", word: "Two", translation: "Hai", emoji: "2️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 2),
        VocabularyCard(id: "number_three", word: "Three", translation: "Ba", emoji: "3️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 3),
        VocabularyCard(id: "number_four", word: "Four", translation: "Bốn", emoji: "4️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 4),
        VocabularyCard(id: "number_five", word: "Five", translation: "Năm", emoji: "5️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 5),
        VocabularyCard(id: "number_six", word: "Six", translation: "Sáu", emoji: "6️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 6),
        VocabularyCard(id: "number_seven", word: "Seven", translation: "Bảy", emoji: "7️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 7),
        VocabularyCard(id: "number_eight", word: "Eight", translation: "Tám", emoji: "8️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 8),
        VocabularyCard(id: "number_nine", word: "Nine", translation: "Chín", emoji: "9️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 9),
        VocabularyCard(id: "number_ten", word: "Ten", translation: "Mười", emoji: "🔟", symbolName: nil, imageName: nil, categoryId: "numbers", value: 10),
    ]

    static func cards(for categoryId: String) -> [VocabularyCard] {
        cards.filter { $0.categoryId == categoryId }
    }
}
