import Foundation

enum VocabularyContent {
    static let categories: [VocabularyCategory] = [
        VocabularyCategory(id: "animals", title: "Con vật", symbolName: "pawprint.fill", imageName: nil, colorHex: "#FF9F43"),
        VocabularyCategory(id: "story", title: "Từ trong truyện", symbolName: "book.fill", imageName: "hoang_tu_va_cao", colorHex: "#4FC3F7"),
        VocabularyCategory(id: "colors", title: "Màu sắc", symbolName: "paintpalette.fill", imageName: nil, colorHex: "#5F27CD"),
        VocabularyCategory(id: "numbers", title: "Số đếm", symbolName: "textformat.123", imageName: nil, colorHex: "#2ED8B6"),
    ]

    static let cards: [VocabularyCard] = [
        VocabularyCard(id: "animal_dog", word: "Dog", translation: "Con chó", emoji: "🐶", symbolName: "dog.fill", imageName: "animal_dog", categoryId: "animals"),
        VocabularyCard(id: "animal_cat", word: "Cat", translation: "Con mèo", emoji: "🐱", symbolName: "cat.fill", imageName: "animal_cat", categoryId: "animals"),
        VocabularyCard(id: "animal_bird", word: "Bird", translation: "Con chim", emoji: "🐦", symbolName: "bird.fill", imageName: "animal_bird", categoryId: "animals"),
        VocabularyCard(id: "animal_fish", word: "Fish", translation: "Con cá", emoji: "🐟", symbolName: "fish.fill", imageName: "animal_fish", categoryId: "animals"),
        VocabularyCard(id: "animal_rabbit", word: "Rabbit", translation: "Con thỏ", emoji: "🐰", symbolName: "hare.fill", imageName: "animal_rabbit", categoryId: "animals"),
        VocabularyCard(id: "animal_bear", word: "Bear", translation: "Con gấu", emoji: "🐻", symbolName: nil, imageName: "animal_bear", categoryId: "animals"),
        VocabularyCard(id: "animal_lion", word: "Lion", translation: "Con sư tử", emoji: "🦁", symbolName: nil, imageName: "animal_lion", categoryId: "animals"),
        VocabularyCard(id: "animal_elephant", word: "Elephant", translation: "Con voi", emoji: "🐘", symbolName: nil, imageName: "animal_elephant", categoryId: "animals"),
        VocabularyCard(id: "animal_hamster", word: "Hamster", translation: "Chuột hamster", emoji: "🐹", symbolName: nil, imageName: "animal_hamster", categoryId: "animals"),
        VocabularyCard(id: "animal_cow", word: "Cow", translation: "Con bò", emoji: "🐄", symbolName: nil, imageName: "animal_cow", categoryId: "animals"),
        VocabularyCard(id: "animal_pig", word: "Pig", translation: "Con lợn", emoji: "🐷", symbolName: nil, imageName: "animal_pig", categoryId: "animals"),
        VocabularyCard(id: "animal_chicken", word: "Chicken", translation: "Con gà", emoji: "🐔", symbolName: nil, imageName: "animal_chicken", categoryId: "animals"),
        VocabularyCard(id: "animal_turkey", word: "Turkey", translation: "Gà tây", emoji: "🦃", symbolName: nil, imageName: "animal_turkey", categoryId: "animals"),
        VocabularyCard(id: "animal_tiger", word: "Tiger", translation: "Con hổ", emoji: "🐯", symbolName: nil, imageName: "animal_tiger", categoryId: "animals"),
        VocabularyCard(id: "animal_gorilla", word: "Gorilla", translation: "Khỉ đột", emoji: "🦍", symbolName: nil, imageName: "animal_gorilla", categoryId: "animals"),
        VocabularyCard(id: "animal_monkey", word: "Monkey", translation: "Con khỉ", emoji: "🐒", symbolName: nil, imageName: "animal_monkey", categoryId: "animals"),
        VocabularyCard(id: "animal_koala", word: "Koala", translation: "Gấu koala", emoji: "🐨", symbolName: nil, imageName: "animal_koala", categoryId: "animals"),
        VocabularyCard(id: "animal_fox", word: "Fox", translation: "Con cáo", emoji: "🦊", symbolName: nil, imageName: "animal_fox", categoryId: "animals"),
        VocabularyCard(id: "animal_deer", word: "Deer", translation: "Con hươu", emoji: "🦌", symbolName: nil, imageName: "animal_deer", categoryId: "animals"),
        VocabularyCard(id: "animal_owl", word: "Owl", translation: "Con cú", emoji: "🦉", symbolName: nil, imageName: "animal_owl", categoryId: "animals"),
        VocabularyCard(id: "animal_parrot", word: "Parrot", translation: "Con vẹt", emoji: "🦜", symbolName: nil, imageName: "animal_parrot", categoryId: "animals"),
        VocabularyCard(id: "animal_penguin", word: "Penguin", translation: "Chim cánh cụt", emoji: "🐧", symbolName: nil, imageName: "animal_penguin", categoryId: "animals"),
        VocabularyCard(id: "animal_flamingo", word: "Flamingo", translation: "Hồng hạc", emoji: "🦩", symbolName: nil, imageName: "animal_flamingo", categoryId: "animals"),
        VocabularyCard(id: "animal_swan", word: "Swan", translation: "Thiên nga", emoji: "🦢", symbolName: nil, imageName: "animal_swan", categoryId: "animals"),
        VocabularyCard(id: "animal_toucan", word: "Toucan", translation: "Chim toucan", emoji: "🐦", symbolName: nil, imageName: "animal_toucan", categoryId: "animals"),
        VocabularyCard(id: "animal_sparrow", word: "Sparrow", translation: "Chim sẻ", emoji: "🐦", symbolName: nil, imageName: "animal_sparrow", categoryId: "animals"),
        VocabularyCard(id: "animal_pelican", word: "Pelican", translation: "Bồ nông", emoji: "🐦", symbolName: nil, imageName: "animal_pelican", categoryId: "animals"),
        VocabularyCard(id: "animal_hummingbird", word: "Hummingbird", translation: "Chim ruồi", emoji: "🐦", symbolName: nil, imageName: "animal_hummingbird", categoryId: "animals"),
        VocabularyCard(id: "animal_whale", word: "Whale", translation: "Cá voi", emoji: "🐋", symbolName: nil, imageName: "animal_whale", categoryId: "animals"),
        VocabularyCard(id: "animal_crab", word: "Crab", translation: "Con cua", emoji: "🦀", symbolName: nil, imageName: "animal_crab", categoryId: "animals"),
        VocabularyCard(id: "animal_lobster", word: "Lobster", translation: "Tôm hùm", emoji: "🦞", symbolName: nil, imageName: "animal_lobster", categoryId: "animals"),
        VocabularyCard(id: "animal_shrimp", word: "Shrimp", translation: "Con tôm", emoji: "🦐", symbolName: nil, imageName: "animal_shrimp", categoryId: "animals"),
        VocabularyCard(id: "animal_jellyfish", word: "Jellyfish", translation: "Sứa biển", emoji: "🪼", symbolName: nil, imageName: "animal_jellyfish", categoryId: "animals"),
        VocabularyCard(id: "animal_starfish", word: "Starfish", translation: "Sao biển", emoji: "⭐", symbolName: nil, imageName: "animal_starfish", categoryId: "animals"),
        VocabularyCard(id: "animal_turtle", word: "Turtle", translation: "Con rùa", emoji: "🐢", symbolName: nil, imageName: "animal_turtle", categoryId: "animals"),
        VocabularyCard(id: "animal_squid", word: "Squid", translation: "Con mực", emoji: "🦑", symbolName: nil, imageName: "animal_squid", categoryId: "animals"),
        VocabularyCard(id: "animal_crocodile", word: "Crocodile", translation: "Cá sấu", emoji: "🐊", symbolName: nil, imageName: "animal_crocodile", categoryId: "animals"),
        VocabularyCard(id: "animal_frog", word: "Frog", translation: "Con ếch", emoji: "🐸", symbolName: nil, imageName: "animal_frog", categoryId: "animals"),
        VocabularyCard(id: "animal_salamander", word: "Salamander", translation: "Kỳ giông", emoji: "🦎", symbolName: nil, imageName: "animal_salamander", categoryId: "animals"),
        VocabularyCard(id: "animal_butterfly", word: "Butterfly", translation: "Con bướm", emoji: "🦋", symbolName: nil, imageName: "animal_butterfly", categoryId: "animals"),
        VocabularyCard(id: "animal_snail", word: "Snail", translation: "Ốc sên", emoji: "🐌", symbolName: nil, imageName: "animal_snail", categoryId: "animals"),
        VocabularyCard(id: "animal_beetle", word: "Beetle", translation: "Bọ cánh cứng", emoji: "🪲", symbolName: nil, imageName: "animal_beetle", categoryId: "animals"),
        VocabularyCard(id: "animal_mouse", word: "Mouse", translation: "Con chuột", emoji: "🐭", symbolName: nil, imageName: "animal_mouse", categoryId: "animals"),
        VocabularyCard(id: "animal_squirrel", word: "Squirrel", translation: "Con sóc", emoji: "🐿️", symbolName: nil, imageName: "animal_squirrel", categoryId: "animals"),
        VocabularyCard(id: "animal_cheetah", word: "Cheetah", translation: "Báo săn", emoji: "🐆", symbolName: nil, imageName: "animal_cheetah", categoryId: "animals"),
        VocabularyCard(id: "animal_rhinoceros", word: "Rhinoceros", translation: "Tê giác", emoji: "🦏", symbolName: nil, imageName: "animal_rhinoceros", categoryId: "animals"),
        VocabularyCard(id: "animal_hippopotamus", word: "Hippopotamus", translation: "Hà mã", emoji: "🦛", symbolName: nil, imageName: "animal_hippopotamus", categoryId: "animals"),
        VocabularyCard(id: "animal_zebra", word: "Zebra", translation: "Ngựa vằn", emoji: "🦓", symbolName: nil, imageName: "animal_zebra", categoryId: "animals"),
        VocabularyCard(id: "animal_donkey", word: "Donkey", translation: "Con lừa", emoji: "🫏", symbolName: nil, imageName: "animal_donkey", categoryId: "animals"),
        VocabularyCard(id: "animal_duck", word: "Duck", translation: "Con vịt", emoji: "🦆", symbolName: nil, imageName: "animal_duck", categoryId: "animals"),
        VocabularyCard(id: "animal_sheep", word: "Sheep", translation: "Con cừu", emoji: "🐑", symbolName: nil, imageName: "animal_sheep", categoryId: "animals"),
        VocabularyCard(id: "animal_horse", word: "Horse", translation: "Con ngựa", emoji: "🐴", symbolName: nil, imageName: "animal_horse", categoryId: "animals"),
        VocabularyCard(id: "animal_eagle", word: "Eagle", translation: "Đại bàng", emoji: "🦅", symbolName: nil, imageName: "animal_eagle", categoryId: "animals"),
        VocabularyCard(id: "animal_camel", word: "Camel", translation: "Lạc đà", emoji: "🐫", symbolName: nil, imageName: "animal_camel", categoryId: "animals"),
        VocabularyCard(id: "animal_wolf", word: "Wolf", translation: "Con sói", emoji: "🐺", symbolName: nil, imageName: "animal_wolf", categoryId: "animals"),
        VocabularyCard(id: "animal_panda", word: "Panda", translation: "Gấu trúc", emoji: "🐼", symbolName: nil, imageName: "animal_panda", categoryId: "animals"),
        VocabularyCard(id: "animal_kangaroo", word: "Kangaroo", translation: "Chuột túi", emoji: "🦘", symbolName: nil, imageName: "animal_kangaroo", categoryId: "animals"),
        VocabularyCard(id: "animal_beaver", word: "Beaver", translation: "Hải ly", emoji: "🦫", symbolName: nil, imageName: "animal_beaver", categoryId: "animals"),
        VocabularyCard(id: "animal_dolphin", word: "Dolphin", translation: "Cá heo", emoji: "🐬", symbolName: nil, imageName: "animal_dolphin", categoryId: "animals"),
        VocabularyCard(id: "animal_scorpion", word: "Scorpion", translation: "Bọ cạp", emoji: "🦂", symbolName: nil, imageName: "animal_scorpion", categoryId: "animals"),
        VocabularyCard(id: "animal_ladybug", word: "Ladybug", translation: "Bọ rùa", emoji: "🐞", symbolName: nil, imageName: "animal_ladybug", categoryId: "animals"),
        VocabularyCard(id: "animal_toad", word: "Toad", translation: "Con cóc", emoji: "🐸", symbolName: nil, imageName: "animal_toad", categoryId: "animals"),
        VocabularyCard(id: "animal_seahorse", word: "Seahorse", translation: "Cá ngựa", emoji: "🐴", symbolName: nil, imageName: "animal_seahorse", categoryId: "animals"),
        VocabularyCard(id: "animal_worm", word: "Worm", translation: "Con giun", emoji: "🪱", symbolName: nil, imageName: "animal_worm", categoryId: "animals"),
        VocabularyCard(id: "animal_bee", word: "Bee", translation: "Con ong", emoji: "🐝", symbolName: nil, imageName: "animal_bee", categoryId: "animals"),
        VocabularyCard(id: "animal_hedgehog", word: "Hedgehog", translation: "Con nhím", emoji: "🦔", symbolName: nil, imageName: "animal_hedgehog", categoryId: "animals"),
        VocabularyCard(id: "animal_snake", word: "Snake", translation: "Con rắn", emoji: "🐍", symbolName: nil, imageName: "animal_snake", categoryId: "animals"),
        VocabularyCard(id: "animal_octopus", word: "Octopus", translation: "Bạch tuộc", emoji: "🐙", symbolName: nil, imageName: "animal_octopus", categoryId: "animals"),
        VocabularyCard(id: "animal_walrus", word: "Walrus", translation: "Hải mã", emoji: "🦭", symbolName: nil, imageName: "animal_walrus", categoryId: "animals"),
        VocabularyCard(id: "animal_shark", word: "Shark", translation: "Cá mập", emoji: "🦈", symbolName: nil, imageName: "animal_shark", categoryId: "animals"),
        VocabularyCard(id: "animal_seal", word: "Seal", translation: "Hải cẩu", emoji: "🦭", symbolName: nil, imageName: "animal_seal", categoryId: "animals"),
        VocabularyCard(id: "animal_chameleon", word: "Chameleon", translation: "Tắc kè hoa", emoji: "🦎", symbolName: nil, imageName: "animal_chameleon", categoryId: "animals"),
        VocabularyCard(id: "animal_moose", word: "Moose", translation: "Nai sừng tấm", emoji: "🫎", symbolName: nil, imageName: "animal_moose", categoryId: "animals"),
        VocabularyCard(id: "animal_bat", word: "Bat", translation: "Con dơi", emoji: "🦇", symbolName: nil, imageName: "animal_bat", categoryId: "animals"),
        VocabularyCard(id: "animal_spider", word: "Spider", translation: "Con nhện", emoji: "🕷️", symbolName: nil, imageName: "animal_spider", categoryId: "animals"),
        VocabularyCard(id: "animal_gecko", word: "Gecko", translation: "Thạch sùng", emoji: "🦎", symbolName: nil, imageName: "animal_gecko", categoryId: "animals"),
        VocabularyCard(id: "animal_firefly", word: "Firefly", translation: "Đom đóm", emoji: "✨", symbolName: nil, imageName: "animal_firefly", categoryId: "animals"),
        VocabularyCard(id: "animal_sloth", word: "Sloth", translation: "Con lười", emoji: "🦥", symbolName: nil, imageName: "animal_sloth", categoryId: "animals"),
        VocabularyCard(id: "animal_mosquito", word: "Mosquito", translation: "Con muỗi", emoji: "🦟", symbolName: nil, imageName: "animal_mosquito", categoryId: "animals"),
        VocabularyCard(id: "animal_ant", word: "Ant", translation: "Con kiến", emoji: "🐜", symbolName: nil, imageName: "animal_ant", categoryId: "animals"),
        VocabularyCard(id: "animal_otter", word: "Otter", translation: "Rái cá", emoji: "🦦", symbolName: nil, imageName: "animal_otter", categoryId: "animals"),
        VocabularyCard(id: "animal_iguana", word: "Iguana", translation: "Kỳ nhông", emoji: "🦎", symbolName: nil, imageName: "animal_iguana", categoryId: "animals"),
        VocabularyCard(id: "animal_raccoon", word: "Raccoon", translation: "Gấu mèo", emoji: "🦝", symbolName: nil, imageName: "animal_raccoon", categoryId: "animals"),
        VocabularyCard(id: "animal_dragonfly", word: "Dragonfly", translation: "Chuồn chuồn", emoji: "🐉", symbolName: nil, imageName: "animal_dragonfly", categoryId: "animals"),
        VocabularyCard(id: "animal_grasshopper", word: "Grasshopper", translation: "Châu chấu", emoji: "🦗", symbolName: nil, imageName: "animal_grasshopper", categoryId: "animals"),
        VocabularyCard(id: "animal_skunk", word: "Skunk", translation: "Chồn hôi", emoji: "🦨", symbolName: nil, imageName: "animal_skunk", categoryId: "animals"),

        VocabularyCard(id: "color_red", word: "Red", translation: "Đỏ", emoji: "🔴", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#E2503F"),
        VocabularyCard(id: "color_blue", word: "Blue", translation: "Xanh dương", emoji: "🔵", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#5B8FC7"),
        VocabularyCard(id: "color_yellow", word: "Yellow", translation: "Vàng", emoji: "🟡", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#E8B84E"),
        VocabularyCard(id: "color_green", word: "Green", translation: "Xanh lá", emoji: "🟢", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#7FB37A"),
        VocabularyCard(id: "color_orange", word: "Orange", translation: "Cam", emoji: "🟠", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#E2924F"),
        VocabularyCard(id: "color_purple", word: "Purple", translation: "Tím", emoji: "🟣", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#A78FC9"),
        VocabularyCard(id: "color_pink", word: "Pink", translation: "Hồng", emoji: "🩷", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#F0A8BE"),
        VocabularyCard(id: "color_black", word: "Black", translation: "Đen", emoji: "⚫", symbolName: "circle.fill", imageName: nil, categoryId: "colors", colorHex: "#6B6660"),

        VocabularyCard(id: "story_fox", word: "Fox", translation: "Con cáo", emoji: "🦊", symbolName: nil, imageName: "ch1_ice_fox", categoryId: "story"),
        VocabularyCard(id: "story_penguin", word: "Penguin", translation: "Chim cánh cụt", emoji: "🐧", symbolName: nil, imageName: "chim_canh_cut_portrait", categoryId: "story"),
        VocabularyCard(id: "story_laugh", word: "Laugh", translation: "Tiếng cười", emoji: "😄", symbolName: nil, imageName: "ch2_penguin_laugh", categoryId: "story"),
        VocabularyCard(id: "story_lantern", word: "Lantern", translation: "Đèn lồng", emoji: "🔦", symbolName: nil, imageName: "den_portrait", categoryId: "story"),
        VocabularyCard(id: "story_brave", word: "Brave", translation: "Dũng cảm", emoji: "🦸", symbolName: nil, imageName: "ch3_lantern_boy", categoryId: "story"),
        VocabularyCard(id: "story_storm", word: "Storm", translation: "Bão tuyết", emoji: "🌪️", symbolName: nil, imageName: "witch_portrait", categoryId: "story"),
        VocabularyCard(id: "story_witch", word: "Witch", translation: "Phù thủy", emoji: "🧙", symbolName: nil, imageName: "witch_portrait", categoryId: "story"),
        VocabularyCard(id: "story_friend", word: "Friend", translation: "Người bạn", emoji: "🤝", symbolName: nil, imageName: "ch5_ending", categoryId: "story"),

        VocabularyCard(id: "number_one", word: "One", translation: "Một", emoji: "1️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 1),
        VocabularyCard(id: "number_two", word: "Two", translation: "Hai", emoji: "2️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 2),
        VocabularyCard(id: "number_three", word: "Three", translation: "Ba", emoji: "3️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 3),
        VocabularyCard(id: "number_four", word: "Four", translation: "Bốn", emoji: "4️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 4),
        VocabularyCard(id: "number_five", word: "Five", translation: "Năm", emoji: "5️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 5),
        VocabularyCard(id: "number_six", word: "Six", translation: "Sáu", emoji: "6️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 6),
        VocabularyCard(id: "number_seven", word: "Seven", translation: "Bảy", emoji: "7️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 7),
        VocabularyCard(id: "number_eight", word: "Eight", translation: "Tám", emoji: "8️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 8),
        VocabularyCard(id: "number_nine", word: "Nine", translation: "Chín", emoji: "9️⃣", symbolName: nil, imageName: nil, categoryId: "numbers", value: 9),
        VocabularyCard(id: "number_ten", word: "Ten", translation: "Mười", emoji: "🔟", symbolName: nil, imageName: nil, categoryId: "numbers", value: 10),
    ]

    static func cards(for categoryId: String) -> [VocabularyCard] {
        cards.filter { $0.categoryId == categoryId }
    }
}
