import Foundation

enum VocabularyContent {
    static let categories: [VocabularyCategory] = [
        VocabularyCategory(id: "animals", title: "Animals", symbolName: "pawprint.fill", imageName: nil, colorHex: "#FF9F43"),
        VocabularyCategory(id: "colors", title: "Colors", symbolName: "paintpalette.fill", imageName: nil, colorHex: "#5F27CD"),
        VocabularyCategory(id: "story", title: "Story Words", symbolName: "book.fill", imageName: "hoang_tu_va_cao", colorHex: "#4FC3F7"),
    ]

    static let cards: [VocabularyCard] = [
        VocabularyCard(id: "animal_dog", word: "Dog", emoji: "🐶", symbolName: "dog.fill", imageName: nil, categoryId: "animals"),
        VocabularyCard(id: "animal_cat", word: "Cat", emoji: "🐱", symbolName: "cat.fill", imageName: nil, categoryId: "animals"),
        VocabularyCard(id: "animal_bird", word: "Bird", emoji: "🐦", symbolName: "bird.fill", imageName: nil, categoryId: "animals"),
        VocabularyCard(id: "animal_fish", word: "Fish", emoji: "🐟", symbolName: "fish.fill", imageName: nil, categoryId: "animals"),
        VocabularyCard(id: "animal_rabbit", word: "Rabbit", emoji: "🐰", symbolName: "hare.fill", imageName: nil, categoryId: "animals"),
        VocabularyCard(id: "animal_bear", word: "Bear", emoji: "🐻", symbolName: nil, imageName: nil, categoryId: "animals"),
        VocabularyCard(id: "animal_lion", word: "Lion", emoji: "🦁", symbolName: nil, imageName: nil, categoryId: "animals"),
        VocabularyCard(id: "animal_elephant", word: "Elephant", emoji: "🐘", symbolName: nil, imageName: nil, categoryId: "animals"),
        VocabularyCard(id: "animal_hamster", word: "Hamster", emoji: "🐹", symbolName: nil, imageName: "animal_hamster", categoryId: "animals"),
        VocabularyCard(id: "animal_cow", word: "Cow", emoji: "🐄", symbolName: nil, imageName: "animal_cow", categoryId: "animals"),
        VocabularyCard(id: "animal_pig", word: "Pig", emoji: "🐷", symbolName: nil, imageName: "animal_pig", categoryId: "animals"),
        VocabularyCard(id: "animal_chicken", word: "Chicken", emoji: "🐔", symbolName: nil, imageName: "animal_chicken", categoryId: "animals"),
        VocabularyCard(id: "animal_turkey", word: "Turkey", emoji: "🦃", symbolName: nil, imageName: "animal_turkey", categoryId: "animals"),
        VocabularyCard(id: "animal_tiger", word: "Tiger", emoji: "🐯", symbolName: nil, imageName: "animal_tiger", categoryId: "animals"),
        VocabularyCard(id: "animal_gorilla", word: "Gorilla", emoji: "🦍", symbolName: nil, imageName: "animal_gorilla", categoryId: "animals"),
        VocabularyCard(id: "animal_monkey", word: "Monkey", emoji: "🐒", symbolName: nil, imageName: "animal_monkey", categoryId: "animals"),
        VocabularyCard(id: "animal_koala", word: "Koala", emoji: "🐨", symbolName: nil, imageName: "animal_koala", categoryId: "animals"),
        VocabularyCard(id: "animal_fox", word: "Fox", emoji: "🦊", symbolName: nil, imageName: "animal_fox", categoryId: "animals"),
        VocabularyCard(id: "animal_deer", word: "Deer", emoji: "🦌", symbolName: nil, imageName: "animal_deer", categoryId: "animals"),
        VocabularyCard(id: "animal_owl", word: "Owl", emoji: "🦉", symbolName: nil, imageName: "animal_owl", categoryId: "animals"),
        VocabularyCard(id: "animal_parrot", word: "Parrot", emoji: "🦜", symbolName: nil, imageName: "animal_parrot", categoryId: "animals"),
        VocabularyCard(id: "animal_penguin", word: "Penguin", emoji: "🐧", symbolName: nil, imageName: "animal_penguin", categoryId: "animals"),
        VocabularyCard(id: "animal_flamingo", word: "Flamingo", emoji: "🦩", symbolName: nil, imageName: "animal_flamingo", categoryId: "animals"),
        VocabularyCard(id: "animal_swan", word: "Swan", emoji: "🦢", symbolName: nil, imageName: "animal_swan", categoryId: "animals"),
        VocabularyCard(id: "animal_toucan", word: "Toucan", emoji: "🐦", symbolName: nil, imageName: "animal_toucan", categoryId: "animals"),
        VocabularyCard(id: "animal_sparrow", word: "Sparrow", emoji: "🐦", symbolName: nil, imageName: "animal_sparrow", categoryId: "animals"),
        VocabularyCard(id: "animal_pelican", word: "Pelican", emoji: "🐦", symbolName: nil, imageName: "animal_pelican", categoryId: "animals"),
        VocabularyCard(id: "animal_hummingbird", word: "Hummingbird", emoji: "🐦", symbolName: nil, imageName: "animal_hummingbird", categoryId: "animals"),
        VocabularyCard(id: "animal_whale", word: "Whale", emoji: "🐋", symbolName: nil, imageName: "animal_whale", categoryId: "animals"),
        VocabularyCard(id: "animal_crab", word: "Crab", emoji: "🦀", symbolName: nil, imageName: "animal_crab", categoryId: "animals"),
        VocabularyCard(id: "animal_lobster", word: "Lobster", emoji: "🦞", symbolName: nil, imageName: "animal_lobster", categoryId: "animals"),
        VocabularyCard(id: "animal_shrimp", word: "Shrimp", emoji: "🦐", symbolName: nil, imageName: "animal_shrimp", categoryId: "animals"),
        VocabularyCard(id: "animal_jellyfish", word: "Jellyfish", emoji: "🪼", symbolName: nil, imageName: "animal_jellyfish", categoryId: "animals"),
        VocabularyCard(id: "animal_starfish", word: "Starfish", emoji: "⭐", symbolName: nil, imageName: "animal_starfish", categoryId: "animals"),
        VocabularyCard(id: "animal_turtle", word: "Turtle", emoji: "🐢", symbolName: nil, imageName: "animal_turtle", categoryId: "animals"),
        VocabularyCard(id: "animal_squid", word: "Squid", emoji: "🦑", symbolName: nil, imageName: "animal_squid", categoryId: "animals"),
        VocabularyCard(id: "animal_crocodile", word: "Crocodile", emoji: "🐊", symbolName: nil, imageName: "animal_crocodile", categoryId: "animals"),
        VocabularyCard(id: "animal_frog", word: "Frog", emoji: "🐸", symbolName: nil, imageName: "animal_frog", categoryId: "animals"),
        VocabularyCard(id: "animal_salamander", word: "Salamander", emoji: "🦎", symbolName: nil, imageName: "animal_salamander", categoryId: "animals"),
        VocabularyCard(id: "animal_butterfly", word: "Butterfly", emoji: "🦋", symbolName: nil, imageName: "animal_butterfly", categoryId: "animals"),
        VocabularyCard(id: "animal_snail", word: "Snail", emoji: "🐌", symbolName: nil, imageName: "animal_snail", categoryId: "animals"),
        VocabularyCard(id: "animal_beetle", word: "Beetle", emoji: "🪲", symbolName: nil, imageName: "animal_beetle", categoryId: "animals"),
        VocabularyCard(id: "animal_mouse", word: "Mouse", emoji: "🐭", symbolName: nil, imageName: "animal_mouse", categoryId: "animals"),
        VocabularyCard(id: "animal_squirrel", word: "Squirrel", emoji: "🐿️", symbolName: nil, imageName: "animal_squirrel", categoryId: "animals"),
        VocabularyCard(id: "animal_cheetah", word: "Cheetah", emoji: "🐆", symbolName: nil, imageName: "animal_cheetah", categoryId: "animals"),
        VocabularyCard(id: "animal_rhinoceros", word: "Rhinoceros", emoji: "🦏", symbolName: nil, imageName: "animal_rhinoceros", categoryId: "animals"),
        VocabularyCard(id: "animal_hippopotamus", word: "Hippopotamus", emoji: "🦛", symbolName: nil, imageName: "animal_hippopotamus", categoryId: "animals"),
        VocabularyCard(id: "animal_zebra", word: "Zebra", emoji: "🦓", symbolName: nil, imageName: "animal_zebra", categoryId: "animals"),
        VocabularyCard(id: "animal_donkey", word: "Donkey", emoji: "🫏", symbolName: nil, imageName: "animal_donkey", categoryId: "animals"),
        VocabularyCard(id: "animal_duck", word: "Duck", emoji: "🦆", symbolName: nil, imageName: "animal_duck", categoryId: "animals"),
        VocabularyCard(id: "animal_sheep", word: "Sheep", emoji: "🐑", symbolName: nil, imageName: "animal_sheep", categoryId: "animals"),
        VocabularyCard(id: "animal_horse", word: "Horse", emoji: "🐴", symbolName: nil, imageName: "animal_horse", categoryId: "animals"),
        VocabularyCard(id: "animal_eagle", word: "Eagle", emoji: "🦅", symbolName: nil, imageName: "animal_eagle", categoryId: "animals"),
        VocabularyCard(id: "animal_camel", word: "Camel", emoji: "🐫", symbolName: nil, imageName: "animal_camel", categoryId: "animals"),
        VocabularyCard(id: "animal_wolf", word: "Wolf", emoji: "🐺", symbolName: nil, imageName: "animal_wolf", categoryId: "animals"),
        VocabularyCard(id: "animal_panda", word: "Panda", emoji: "🐼", symbolName: nil, imageName: "animal_panda", categoryId: "animals"),
        VocabularyCard(id: "animal_kangaroo", word: "Kangaroo", emoji: "🦘", symbolName: nil, imageName: "animal_kangaroo", categoryId: "animals"),
        VocabularyCard(id: "animal_beaver", word: "Beaver", emoji: "🦫", symbolName: nil, imageName: "animal_beaver", categoryId: "animals"),
        VocabularyCard(id: "animal_dolphin", word: "Dolphin", emoji: "🐬", symbolName: nil, imageName: "animal_dolphin", categoryId: "animals"),
        VocabularyCard(id: "animal_scorpion", word: "Scorpion", emoji: "🦂", symbolName: nil, imageName: "animal_scorpion", categoryId: "animals"),
        VocabularyCard(id: "animal_ladybug", word: "Ladybug", emoji: "🐞", symbolName: nil, imageName: "animal_ladybug", categoryId: "animals"),
        VocabularyCard(id: "animal_toad", word: "Toad", emoji: "🐸", symbolName: nil, imageName: "animal_toad", categoryId: "animals"),
        VocabularyCard(id: "animal_seahorse", word: "Seahorse", emoji: "🐴", symbolName: nil, imageName: "animal_seahorse", categoryId: "animals"),
        VocabularyCard(id: "animal_worm", word: "Worm", emoji: "🪱", symbolName: nil, imageName: "animal_worm", categoryId: "animals"),
        VocabularyCard(id: "animal_bee", word: "Bee", emoji: "🐝", symbolName: nil, imageName: "animal_bee", categoryId: "animals"),
        VocabularyCard(id: "animal_hedgehog", word: "Hedgehog", emoji: "🦔", symbolName: nil, imageName: "animal_hedgehog", categoryId: "animals"),
        VocabularyCard(id: "animal_snake", word: "Snake", emoji: "🐍", symbolName: nil, imageName: "animal_snake", categoryId: "animals"),
        VocabularyCard(id: "animal_octopus", word: "Octopus", emoji: "🐙", symbolName: nil, imageName: "animal_octopus", categoryId: "animals"),
        VocabularyCard(id: "animal_walrus", word: "Walrus", emoji: "🦭", symbolName: nil, imageName: "animal_walrus", categoryId: "animals"),
        VocabularyCard(id: "animal_shark", word: "Shark", emoji: "🦈", symbolName: nil, imageName: "animal_shark", categoryId: "animals"),
        VocabularyCard(id: "animal_seal", word: "Seal", emoji: "🦭", symbolName: nil, imageName: "animal_seal", categoryId: "animals"),
        VocabularyCard(id: "animal_chameleon", word: "Chameleon", emoji: "🦎", symbolName: nil, imageName: "animal_chameleon", categoryId: "animals"),
        VocabularyCard(id: "animal_moose", word: "Moose", emoji: "🫎", symbolName: nil, imageName: "animal_moose", categoryId: "animals"),
        VocabularyCard(id: "animal_bat", word: "Bat", emoji: "🦇", symbolName: nil, imageName: "animal_bat", categoryId: "animals"),
        VocabularyCard(id: "animal_spider", word: "Spider", emoji: "🕷️", symbolName: nil, imageName: "animal_spider", categoryId: "animals"),
        VocabularyCard(id: "animal_gecko", word: "Gecko", emoji: "🦎", symbolName: nil, imageName: "animal_gecko", categoryId: "animals"),
        VocabularyCard(id: "animal_firefly", word: "Firefly", emoji: "✨", symbolName: nil, imageName: "animal_firefly", categoryId: "animals"),
        VocabularyCard(id: "animal_sloth", word: "Sloth", emoji: "🦥", symbolName: nil, imageName: "animal_sloth", categoryId: "animals"),
        VocabularyCard(id: "animal_mosquito", word: "Mosquito", emoji: "🦟", symbolName: nil, imageName: "animal_mosquito", categoryId: "animals"),
        VocabularyCard(id: "animal_ant", word: "Ant", emoji: "🐜", symbolName: nil, imageName: "animal_ant", categoryId: "animals"),
        VocabularyCard(id: "animal_otter", word: "Otter", emoji: "🦦", symbolName: nil, imageName: "animal_otter", categoryId: "animals"),
        VocabularyCard(id: "animal_iguana", word: "Iguana", emoji: "🦎", symbolName: nil, imageName: "animal_iguana", categoryId: "animals"),
        VocabularyCard(id: "animal_raccoon", word: "Raccoon", emoji: "🦝", symbolName: nil, imageName: "animal_raccoon", categoryId: "animals"),
        VocabularyCard(id: "animal_dragonfly", word: "Dragonfly", emoji: "🐉", symbolName: nil, imageName: "animal_dragonfly", categoryId: "animals"),
        VocabularyCard(id: "animal_grasshopper", word: "Grasshopper", emoji: "🦗", symbolName: nil, imageName: "animal_grasshopper", categoryId: "animals"),
        VocabularyCard(id: "animal_skunk", word: "Skunk", emoji: "🦨", symbolName: nil, imageName: "animal_skunk", categoryId: "animals"),

        VocabularyCard(id: "color_red", word: "Red", emoji: "🔴", symbolName: "circle.fill", imageName: nil, categoryId: "colors"),
        VocabularyCard(id: "color_blue", word: "Blue", emoji: "🔵", symbolName: "circle.fill", imageName: nil, categoryId: "colors"),
        VocabularyCard(id: "color_yellow", word: "Yellow", emoji: "🟡", symbolName: "circle.fill", imageName: nil, categoryId: "colors"),
        VocabularyCard(id: "color_green", word: "Green", emoji: "🟢", symbolName: "circle.fill", imageName: nil, categoryId: "colors"),
        VocabularyCard(id: "color_orange", word: "Orange", emoji: "🟠", symbolName: "circle.fill", imageName: nil, categoryId: "colors"),
        VocabularyCard(id: "color_purple", word: "Purple", emoji: "🟣", symbolName: "circle.fill", imageName: nil, categoryId: "colors"),
        VocabularyCard(id: "color_pink", word: "Pink", emoji: "🩷", symbolName: "circle.fill", imageName: nil, categoryId: "colors"),
        VocabularyCard(id: "color_black", word: "Black", emoji: "⚫", symbolName: "circle.fill", imageName: nil, categoryId: "colors"),

        VocabularyCard(id: "story_fox", word: "Fox", emoji: "🦊", symbolName: nil, imageName: "ch1_ice_fox", categoryId: "story"),
        VocabularyCard(id: "story_penguin", word: "Penguin", emoji: "🐧", symbolName: nil, imageName: "chim_canh_cut_portrait", categoryId: "story"),
        VocabularyCard(id: "story_laugh", word: "Laugh", emoji: "😄", symbolName: nil, imageName: "ch2_penguin_laugh", categoryId: "story"),
        VocabularyCard(id: "story_lantern", word: "Lantern", emoji: "🔦", symbolName: nil, imageName: "den_portrait", categoryId: "story"),
        VocabularyCard(id: "story_brave", word: "Brave", emoji: "🦸", symbolName: nil, imageName: "ch3_lantern_boy", categoryId: "story"),
        VocabularyCard(id: "story_storm", word: "Storm", emoji: "🌪️", symbolName: nil, imageName: "witch_portrait", categoryId: "story"),
        VocabularyCard(id: "story_witch", word: "Witch", emoji: "🧙", symbolName: nil, imageName: "witch_portrait", categoryId: "story"),
        VocabularyCard(id: "story_friend", word: "Friend", emoji: "🤝", symbolName: nil, imageName: "ch5_ending", categoryId: "story"),
    ]

    static func cards(for categoryId: String) -> [VocabularyCard] {
        cards.filter { $0.categoryId == categoryId }
    }
}
